import type { Metadata } from "next";




import MyHeader from "@/components/component/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PanelLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <MyHeader />
    { children }
    </>
  );
}
