/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jFmmXPsV2mg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Chivo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"

export function TestComponent() {
  return (
    <div className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900">
      <header className="bg-white dark:bg-gray-800 shadow">
        <div className="container mx-auto px-4 py-4 md:py-6 flex items-center justify-between">
          <div className="flex items-center">
            <Link className="text-gray-900 dark:text-gray-100 font-bold text-xl" href="#">
              Acme Deployment
            </Link>
          </div>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100" href="#">
              Features
            </Link>
            <Link className="text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100" href="#">
              Pricing
            </Link>
            <Link className="text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100" href="#">
              Docs
            </Link>
            <Link className="text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100" href="#">
              Contact
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Button className="hidden md:inline-flex" variant="outline">
              Sign In
            </Button>
            <Button className="hidden md:inline-flex">Get Started</Button>
            <Button className="md:hidden" size="icon" variant="ghost">
              <MenuIcon className="h-6 w-6" />
            </Button>
          </div>
        </div>
      </header>
      <main className="flex-1 py-12 md:py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900 dark:text-gray-100 mb-4">
              Deploy Your App with Ease
            </h1>
            <p className="text-gray-600 dark:text-gray-400 mb-8">
              Enter your Git repository URL and we'll handle the rest. Track the progress of your deployment in
              real-time.
            </p>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6 md:p-8 mb-8">
              <form className="space-y-4">
                <div>
                  <Label className="block text-gray-700 dark:text-gray-300 font-medium mb-2" htmlFor="repository-url">
                    Git Repository URL
                  </Label>
                  <Input
                    className="w-full border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                    id="repository-url"
                    placeholder="https://github.com/your-username/your-repo.git"
                    type="text"
                  />
                </div>
                <Button className="w-full">Deploy Now</Button>
              </form>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6 md:p-8">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg md:text-xl font-bold text-gray-900 dark:text-gray-100">Deployment Status</h2>
                <div className="flex items-center space-x-2">
                  <Badge className="bg-green-500 text-white" variant="secondary">
                    Successful
                  </Badge>
                  <span className="text-gray-600 dark:text-gray-400 text-sm">10 minutes ago</span>
                </div>
              </div>
              <div className="flex items-center space-x-4">
                <div className="flex-1">
                  <Progress className="h-4" value={100} />
                  <div className="text-gray-600 dark:text-gray-400 text-sm mt-2">Deployment completed</div>
                </div>
                <Button className="shrink-0" variant="outline">
                  View Logs
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="bg-gray-900 text-gray-400 py-8">
        <div className="container mx-auto px-4 flex flex-col md:flex-row items-center justify-between">
          <div className="mb-4 md:mb-0">
            <Link className="text-white font-bold text-xl" href="#">
              Acme Deployment
            </Link>
          </div>
          <nav className="flex items-center space-x-6">
            <Link className="hover:text-gray-100" href="#">
              Features
            </Link>
            <Link className="hover:text-gray-100" href="#">
              Pricing
            </Link>
            <Link className="hover:text-gray-100" href="#">
              Docs
            </Link>
            <Link className="hover:text-gray-100" href="#">
              Contact
            </Link>
          </nav>
          <div className="text-sm">© 2024 Acme Inc. All rights reserved.</div>
        </div>
      </footer>
    </div>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
